'use client';
import localFont from 'next/font/local';
import './globals.css';
import Link from 'next/link';
import { UserProfileDropdown } from '@/features/auth/UserProfileDropdown';
import { AuthGuard } from '@/features/auth/AuthGuard';
import { AuthSignInButton } from '@/features/auth/AuthSignInButton';
import { Backpack } from 'lucide-react';
import { QueryClient, QueryClientProvider } from 'react-query';
import { SupabaseGearProvider } from '@/features/gear/SupabaseGearProvider';
import { useMemo } from 'react';

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
});
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
});

const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const queryClient = useMemo(() => new QueryClient(), []);

    return (
        <html lang='en'>
            <head>
                <title>{metadata.title}</title>
                <meta name='description' content={metadata.description} />
                <link rel='icon' href='/favicon.ico' />
            </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <QueryClientProvider client={queryClient}>
                    <div className='min-h-screen flex flex-col'>
                        <header className='border-b sticky top-0 bg-background z-30'>
                            <div className='m-auto px-4 sm:px-6 h-14 flex items-center max-w-7xl'>
                                <Link
                                    className='flex items-center justify-center'
                                    href='/'
                                >
                                    <Backpack className='h-6 w-6' />
                                    <span className='ml-2 text-2xl font-bold'>
                                        packapack.co
                                    </span>
                                </Link>
                                <nav className='ml-auto flex items-center gap-4 sm:gap-6'>
                                    <Link
                                        className='text-sm font-medium hover:underline underline-offset-4'
                                        href='/packs'
                                    >
                                        Packs
                                    </Link>
                                    <Link
                                        className='text-sm font-medium hover:underline underline-offset-4'
                                        href='/gear'
                                    >
                                        Gear
                                    </Link>
                                    <Link
                                        className='text-sm font-medium hover:underline underline-offset-4'
                                        href='#'
                                    >
                                        Community
                                    </Link>
                                    <AuthGuard fallback={<AuthSignInButton />}>
                                        <UserProfileDropdown />
                                    </AuthGuard>
                                </nav>{' '}
                            </div>
                        </header>
                        <main className='max-w-7xl flex-grow container mx-auto px-4 sm:px-6 py-8'>
                            <SupabaseGearProvider>
                                {children}
                            </SupabaseGearProvider>
                        </main>
                        <footer className='bg-gray-100'>
                            <div className='max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 text-center text-gray-500'>
                                © 2024 packapack.co. All rights reserved.
                            </div>
                        </footer>
                    </div>
                </QueryClientProvider>
            </body>
        </html>
    );
}
