export const gearToUpload = [
    {
        name: 'MSR PocketRocket 2',
        price: 50,
        description: '',
        brand: 'MSR',
        image: '',
        weight: 0,
    },
    {
        name: 'Jetboil Flash Cooking System',
        price: 130,
        description: '',
        brand: 'Jetboil',
        image: '',
        weight: 0,
    },
    {
        name: 'Soto Amicus Stove Cookset',
        price: 50,
        description: '',
        brand: 'Soto',
        image: '',
        weight: 0,
    },
    {
        name: 'MSR Reactor 2.5L System',
        price: 310,
        description: '',
        brand: 'MSR',
        image: '',
        weight: 0,
    },
    {
        name: 'Jetboil MiniMo System',
        price: 170,
        description: '',
        brand: 'Jetboil',
        image: '',
        weight: 0,
    },
    {
        name: 'MSR WhisperLite Universal',
        price: 200,
        description: '',
        brand: 'MSR',
        image: '',
        weight: 0,
    },
    {
        name: 'Solo Stove Lite',
        price: 70,
        description: '',
        brand: 'Solo Stove',
        image: '',
        weight: 0,
    },
    {
        name: 'MSR WindBurner System',
        price: 190,
        description: '',
        brand: 'MSR',
        image: '',
        weight: 0,
    },
    {
        name: 'Soto WindMaster Stove',
        price: 70,
        description: '',
        brand: 'Soto',
        image: '',
        weight: 0,
    },
    {
        name: 'Solo Stove Alcohol Burner',
        price: 20,
        description: '',
        brand: 'Solo Stove',
        image: '',
        weight: 0,
    },
    {
        name: 'OliCamp Ion w/ Titanium Mug',
        price: 85,
        description: '',
        brand: 'OliCamp',
        image: '',
        weight: 0,
    },
    {
        name: 'Snow Peak LiteMax',
        price: 50,
        description: '',
        brand: 'Snow Peak',
        image: '',
        weight: 0,
    },
    {
        name: 'OliCamp Generator Remote Stove',
        price: 60,
        description: '',
        brand: 'OliCamp',
        image: '',
        weight: 0,
    },
    {
        name: 'Jetboil Stash Cooking System',
        price: 150,
        description: '',
        brand: 'Jetboil',
        image: '',
        weight: 0,
    },
    {
        name: 'BRS 3000T',
        price: 17,
        description: '',
        brand: 'BRS',
        image: '',
        weight: 0,
    },
    {
        name: 'Esbit Pocket Stove',
        price: 16,
        description: '',
        brand: 'Esbit',
        image: '',
        weight: 0,
    },
];
